### PR TITLE
Added ability to push and pull

### PR DESCRIPTION
**Pull request by visualcookie**
Created two mixins for the new push and pull classes. This method is used by almost any grid.

Guess Issue #2 can be closed after merged.

### CODE REVIEW

**Comment by esr360** [comment]
Great, awesome stuff. 

We need to get this code into the source Scss files though so that these push/pull classes are created dynamically. Looking at how you've done it, it shouldn't be too difficult. I will have a play this weekend, unless you would like to give it a go?

Also a nice way to avoid repeating `position: relative;` on each push/pull class might be to do something like:

``` scss
[class*="push-"],
[class*="pull-"] {
    position: relative;
}
```

**Comment by visualcookie** [comment]
Will get into it. Totally missed that out. Only added it to flow-row.

Gonna see if I'm able to get it done by Sunday.

**Comment by visualcookie** [comment]
I modified the push and pull a bit and inserted the source to line 274 in the `kayzen-gs.scss`. Got one problem there now. If the column is pulled, there's still a `margin-left`. I don't want to use `!important` for that. Maybe you got a clue.

**Comment by esr360** [comment]
I agree not to use !important, it can most likely be achieved without.

I've been thinking about this in the back of my mind since you posted, I'll take a proper look at your commits when I next have time, probably this weekend, and we can get it sorted then :)

**Comment by esr360** [comment]
Branch version_2_beta has ability to push and pull columns. Not quite ready for use yet but won't be long before an official release with the feature.

**Comment by esr360** [comment]
Ability to push and pull columns is now available on master branch through version 2. Thanks for the idea!

**Pull request closed without merging**
